package com.demo.seata;

import io.seata.spring.annotation.GlobalTransactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Seata demo: demonstrates @GlobalTransactional for distributed transactions.
 * The inspector can read Seata config even without a running TC server.
 */
@Service
public class SeataOrderService {

    private static final Logger log = LoggerFactory.getLogger(SeataOrderService.class);

    @Autowired
    private JdbcTemplate jdbcTemplate;

    /**
     * Simulates a global distributed transaction across multiple services.
     * The @GlobalTransactional annotation is visible to SeataInspector.
     */
    @GlobalTransactional(name = "createOrder", timeoutMills = 60000, rollbackFor = Exception.class)
    public String createOrder(String customerName, String product, int quantity) {
        log.info("Seata global TX started: creating order for {}", customerName);

        // Step 1: Insert into orders table (branch transaction 1)
        jdbcTemplate.update(
                "INSERT INTO seata_orders (customer_name, product, quantity, status) VALUES (?, ?, ?, 'PENDING')",
                customerName, product, quantity);

        // Step 2: Insert into inventory table (branch transaction 2)
        jdbcTemplate.update(
                "INSERT INTO seata_inventory (product, deducted_qty) VALUES (?, ?)",
                product, quantity);

        log.info("Seata global TX completed: order created for {} x{} {}", customerName, quantity, product);
        return "Order created via global transaction [XID auto-generated by Seata]";
    }
}
