[libdefaults]
    default_realm = DEMO.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    forwardable = yes
    renewable = yes

[realms]
    DEMO.LOCAL = {
        kdc = localhost:88
        admin_server = localhost:749
        default_domain = demo.local
    }

[domain_realm]
    .demo.local = DEMO.LOCAL
    demo.local = DEMO.LOCAL
    localhost = DEMO.LOCAL

[logging]
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log
