package com.demo.kerberos;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.FileSystemResource;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.ProviderManager;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.kerberos.authentication.KerberosServiceAuthenticationProvider;
import org.springframework.security.kerberos.authentication.sun.SunJaasKerberosTicketValidator;
import org.springframework.security.kerberos.web.authentication.SpnegoAuthenticationProcessingFilter;
import org.springframework.security.kerberos.web.authentication.SpnegoEntryPoint;
import org.springframework.security.provisioning.InMemoryUserDetailsManager;

import java.util.Arrays;
import java.util.Collections;

/**
 * Real Kerberos/SPNEGO security configuration for KerberosInspector demo.
 *
 * Requires the MIT Kerberos KDC running in Docker (demo-kdc container).
 * The keytab is generated by docker/kdc/init-kdc.sh and mounted at
 * docker/kdc/keytabs/demo.keytab.
 *
 * Beans created (all visible to KerberosInspector):
 *  - SunJaasKerberosTicketValidator   (validates SPNEGO tickets against keytab)
 *  - KerberosServiceAuthenticationProvider (maps Kerberos principals to users)
 *  - SpnegoAuthenticationProcessingFilter  (extracts SPNEGO tokens from HTTP)
 *  - SpnegoEntryPoint                      (initiates SPNEGO challenge)
 *  - UserDetailsService                    (maps principals to roles)
 */
@Configuration
@ConditionalOnProperty(name = "kerberos.enabled", havingValue = "true", matchIfMissing = false)
public class KerberosSecurityConfig {

    private static final Logger log = LoggerFactory.getLogger(KerberosSecurityConfig.class);

    @Value("${spring.security.kerberos.service-principal}")
    private String servicePrincipal;

    @Value("${spring.security.kerberos.keytab-location}")
    private String keytabLocation;

    @Value("${kerberos.keytab-path:docker/kdc/keytabs/demo.keytab}")
    private String keytabPath;

    // ==================================================================
    //  Ticket Validator
    // ==================================================================

    @Bean
    public SunJaasKerberosTicketValidator sunJaasKerberosTicketValidator() {
        SunJaasKerberosTicketValidator validator = new SunJaasKerberosTicketValidator();
        validator.setServicePrincipal(servicePrincipal);
        validator.setKeyTabLocation(new FileSystemResource(keytabPath));
        validator.setDebug(true);
        log.info("Kerberos ticket validator configured: principal={}, keytab={}",
                servicePrincipal, keytabPath);
        return validator;
    }

    // ==================================================================
    //  User Details Service (maps Kerberos principals to Spring users)
    // ==================================================================

    @Bean
    public UserDetailsService kerberosUserDetailsService() {
        UserDetails demoUser = User.withUsername("demo-user@DEMO.LOCAL")
                .password("dummy")
                .authorities(new SimpleGrantedAuthority("ROLE_USER"))
                .build();

        UserDetails adminUser = User.withUsername("demo-admin@DEMO.LOCAL")
                .password("dummy")
                .authorities(new SimpleGrantedAuthority("ROLE_USER"),
                             new SimpleGrantedAuthority("ROLE_ADMIN"))
                .build();

        UserDetails httpService = User.withUsername("HTTP/localhost@DEMO.LOCAL")
                .password("dummy")
                .authorities(new SimpleGrantedAuthority("ROLE_SERVICE"))
                .build();

        log.info("Kerberos user details service: {} users configured", 3);
        return new InMemoryUserDetailsManager(Arrays.asList(demoUser, adminUser, httpService));
    }

    // ==================================================================
    //  Authentication Provider
    // ==================================================================

    @Bean
    public KerberosServiceAuthenticationProvider kerberosServiceAuthenticationProvider() {
        KerberosServiceAuthenticationProvider provider = new KerberosServiceAuthenticationProvider();
        provider.setTicketValidator(sunJaasKerberosTicketValidator());
        provider.setUserDetailsService(kerberosUserDetailsService());
        log.info("Kerberos authentication provider configured");
        return provider;
    }

    // ==================================================================
    //  SPNEGO Entry Point
    // ==================================================================

    @Bean
    public SpnegoEntryPoint spnegoEntryPoint() {
        return new SpnegoEntryPoint("/login");
    }

    // ==================================================================
    //  SPNEGO Authentication Filter
    // ==================================================================

    @Bean
    public AuthenticationManager kerberosAuthenticationManager() {
        return new ProviderManager(kerberosServiceAuthenticationProvider());
    }

    @Bean
    public SpnegoAuthenticationProcessingFilter spnegoAuthenticationProcessingFilter() {
        SpnegoAuthenticationProcessingFilter filter = new SpnegoAuthenticationProcessingFilter();
        filter.setAuthenticationManager(kerberosAuthenticationManager());
        return filter;
    }
}
